// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKG_CJ0VCje4zOe5dOTr7aBzaj5MTbFXo',
    appId: '1:5104112793:web:aed0ce4a032c6774bcd408',
    messagingSenderId: '5104112793',
    projectId: 'appmoviliii',
    authDomain: 'appmoviliii.firebaseapp.com',
    databaseURL: 'https://appmoviliii-default-rtdb.firebaseio.com',
    storageBucket: 'appmoviliii.firebasestorage.app',
    measurementId: 'G-HZXE1BT7XZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALuntr8VTlshRKJIz7fWF1XB5aQTGI06k',
    appId: '1:5104112793:android:016cfcda8541281ebcd408',
    messagingSenderId: '5104112793',
    projectId: 'appmoviliii',
    databaseURL: 'https://appmoviliii-default-rtdb.firebaseio.com',
    storageBucket: 'appmoviliii.firebasestorage.app',
  );
}
